image: adoptopenjdk/openjdk15:latest

stages:
  - build
  - test
  - deploy

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script: ./gradlew assemble
  artifacts:
    paths:
      - build/libs/doctorsregistry-0.0.1-SNAPSHOT.jar

test:
  stage: test
  script: ./gradlew test

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -yq
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    - dpl --provider=heroku --app=msemitkin-doctorsregistry --api-key=$HEROKU_API_KEY
  only:
    - master