image: adoptopenjdk/openjdk15:latest

stages:
  - build
  - test

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs/doctorsregistry-0.0.1-SNAPSHOT.jar

test:
  stage: test
  script: ./gradlew test