image: adoptopenjdk/openjdk11:latest

stages:
  - build

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs/doctorsregistry-0.0.1-SNAPSHOT.jar